using System.Collections.Generic;

namespace DotaReplayConsole
{
    public class Player
    {
        public long match_id { get; set; }
        public int player_slot { get; set; }
        //public List<int> ability_upgrades_arr { get; set; }
        //public AbilityUses ability_uses { get; set; }
        //public AbilityTargets ability_targets { get; set; }
        //public DamageTargets damage_targets { get; set; }
        //public int account_id { get; set; }
        //public Actions actions { get; set; }
        //public AdditionalUnits additional_units { get; set; }
        //public int assists { get; set; }
        //public int backpack_0 { get; set; }
        //public int backpack_1 { get; set; }
        //public int backpack_2 { get; set; }
        //public List<BuybackLog> buyback_log { get; set; }
        //public int camps_stacked { get; set; }
        //public List<ConnectionLog> connection_log { get; set; }
        //public int creeps_stacked { get; set; }
        //public Damage damage { get; set; }
        //public DamageInflictor damage_inflictor { get; set; }
        //public DamageInflictorReceived damage_inflictor_received { get; set; }
        //public DamageTaken damage_taken { get; set; }
        //public int deaths { get; set; }
        //public int denies { get; set; }
        //public List<int> dn_t { get; set; }
        //public int gold { get; set; }
        //public int gold_per_min { get; set; }
        //public GoldReasons gold_reasons { get; set; }
        //public int gold_spent { get; set; }
        //public List<int> gold_t { get; set; }
        //public int hero_damage { get; set; }
        //public int hero_healing { get; set; }
        //public HeroHits hero_hits { get; set; }
        public int hero_id { get; set; }
        //public int item_0 { get; set; }
        //public int item_1 { get; set; }
        //public int item_2 { get; set; }
        //public int item_3 { get; set; }
        //public int item_4 { get; set; }
        //public int item_5 { get; set; }
        //public ItemUses item_uses { get; set; }
        //public KillStreaks kill_streaks { get; set; }
        //public Killed killed { get; set; }
        //public KilledBy killed_by { get; set; }
        //public int kills { get; set; }
        //public List<KillsLog> kills_log { get; set; }
        //public LanePos lane_pos { get; set; }
        //public int last_hits { get; set; }
        //public int leaver_status { get; set; }
        //public int level { get; set; }
        //public List<int> lh_t { get; set; }
        //public LifeState life_state { get; set; }
        //public MaxHeroHit max_hero_hit { get; set; }
        //public MultiKills multi_kills { get; set; }
        //public Obs obs { get; set; }
        //public List<ObsLeftLog> obs_left_log { get; set; }
        //public List<ObsLog> obs_log { get; set; }
        //public int obs_placed { get; set; }
        //public int party_id { get; set; }
        //public List<PermanentBuff> permanent_buffs { get; set; }
        //public int pings { get; set; }
        //public Purchase purchase { get; set; }
        //public List<PurchaseLog> purchase_log { get; set; }
        //public int rune_pickups { get; set; }
        //public Runes runes { get; set; }
        //public List<RunesLog> runes_log { get; set; }
        //public Sen sen { get; set; }
        //public List<SenLeftLog> sen_left_log { get; set; }
        //public List<SenLog> sen_log { get; set; }
        //public int sen_placed { get; set; }
        //public int stuns { get; set; }
        //public List<int> times { get; set; }
        //public int tower_damage { get; set; }
        //public int xp_per_min { get; set; }
        //public XpReasons xp_reasons { get; set; }
        //public List<int> xp_t { get; set; }
        //public string personaname { get; set; }
        //public string name { get; set; }
        //public object last_login { get; set; }
        //public bool radiant_win { get; set; }
        //public int start_time { get; set; }
        //public int duration { get; set; }
        //public int cluster { get; set; }
        //public int lobby_type { get; set; }
        //public int game_mode { get; set; }
        //public int patch { get; set; }
        //public int region { get; set; }
        //public bool isRadiant { get; set; }
        //public int win { get; set; }
        //public int lose { get; set; }
        //public int total_gold { get; set; }
        //public int total_xp { get; set; }
        //public int kills_per_min { get; set; }
        //public int kda { get; set; }
        //public int abandons { get; set; }
        //public int neutral_kills { get; set; }
        //public int tower_kills { get; set; }
        //public int courier_kills { get; set; }
        //public int lane_kills { get; set; }
        //public int hero_kills { get; set; }
        //public int observer_kills { get; set; }
        //public int sentry_kills { get; set; }
        //public int roshan_kills { get; set; }
        //public int necronomicon_kills { get; set; }
        //public int ancient_kills { get; set; }
        //public int buyback_count { get; set; }
        //public int observer_uses { get; set; }
        //public int sentry_uses { get; set; }
        //public int lane_efficiency { get; set; }
        //public int lane_efficiency_pct { get; set; }
        //public int lane { get; set; }
        //public int lane_role { get; set; }
        //public bool is_roaming { get; set; }
        //public PurchaseTime purchase_time { get; set; }
        //public FirstPurchaseTime first_purchase_time { get; set; }
        //public ItemWin item_win { get; set; }
        //public ItemUsage item_usage { get; set; }
        //public PurchaseTpScroll purchase_tpscroll { get; set; }
        //public int actions_per_min { get; set; }
        //public int life_state_dead { get; set; }
        //public int rank_tier { get; set; }
        //public List<int> cosmetics { get; set; }
        //public Benchmarks benchmarks { get; set; }
    }
}
